- hosts: localhost
  connection: local

  tasks:
    - name: create a cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "us-east-1"
        disable_rollback: true
        template: "s3bucket.yaml"
        tags:
          Stack: "ansible-cloudformation"
